name: Unit and Integration Tests
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Get go cache locations
        id: get-go-caches
        run: |
          echo "gocache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      - name: Cache go
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.get-go-caches.outputs.gocache }}
            ${{ steps.get-go-caches.outputs.gomodcache }}
          key: ${{ runner.os }}-go${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}

      - name: Download dependencies
        run: go mod download

      - name: Run unit and integration tests
        run: go test -race -tags=integration ./...

      - name: Build
        run: go build -v ./cmd/gh

  integration-tests:
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build executable
        run: make

      - name: Run attestation command integration Tests
        run: |
          ./test/integration/attestation-cmd/download-and-verify-package-attestation.sh
          ./test/integration/attestation-cmd/verify-sigstore-bundle-versions.sh
